version: '3.5'
services:
    nats:
        image: nats
        ports:
            - '8222:8222' # monitoring UI
            - '4222:4222' # client connection
        command: >
            -js
            --http_port 8222
        networks: ['nats']

networks:
    nats:
        name: nats
